# Generated by Django 5.1.5 on 2026-04-24 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GateEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("ENTRY", "Entry"), ("EXIT", "Exit")], max_length=10
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("BIOMETRIC", "Facial Recognition"),
                            ("CARD", "University Card"),
                            ("RETINA", "Retina Scan"),
                            ("MANUAL", "Manual Override"),
                        ],
                        default="BIOMETRIC",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gate Entry",
                "verbose_name_plural": "Gate Entries",
                "db_table": "gate_entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="gate_entrie_user_id_162f69_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="gate_entrie_timesta_e5437a_idx"
                    ),
                ],
            },
        ),
    ]
