# Generated by Django 5.1.5 on 2026-04-27 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.BinaryField()),
                ('frame_embeddings', models.JSONField(blank=True, default=list)),
                ('frame_count', models.IntegerField(default=5)),
                ('quality_score', models.FloatField(help_text='0.0–1.0, average sharpness × brightness × face-size composite')),
                ('quality_grade', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable')], default='GOOD', max_length=20)),
                ('liveness_passed', models.BooleanField(default=False, help_text='Anti-spoof check passed during enrollment')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('REPLACED', 'Replaced by new enrollment'), ('ADMIN_REMOVED', 'Removed by administrator'), ('USER_REQUEST', 'Removed at user request'), ('QUALITY_ISSUE', 'Removed due to recognition issues'), ('ACCOUNT_DEACTIVATED', 'User account deactivated')], max_length=50)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_deactivated', to=settings.AUTH_USER_MODEL)),
                ('enrolled_by', models.ForeignKey(help_text='Admin who performed the enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Enrollment',
                'verbose_name_plural': 'Face Enrollments',
                'db_table': 'face_enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='face_enroll_user_id_791dd5_idx'), models.Index(fields=['enrolled_at'], name='face_enroll_enrolle_520352_idx'), models.Index(fields=['is_active', 'enrolled_at'], name='face_enroll_is_acti_d1786f_idx')],
            },
        ),
    ]
