# Generated by Django 5.1.5 on 2026-04-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_faceenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, help_text='e.g. "Lahore Campus"', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='card_issued_on',
            field=models.CharField(blank=True, help_text='As printed on card, e.g. "SEP-2022"', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='card_serial_no',
            field=models.CharField(blank=True, help_text='Card serial / S.No on the back', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='card_valid_upto',
            field=models.CharField(blank=True, help_text='As printed on card, e.g. "SEP-2028"', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(blank=True, db_index=True, help_text='Printed registration / enrollment number on the campus card (e.g. "03-134222-110"). Distinct from the auto-generated university_id which is internal-only.', max_length=30, null=True, unique=True),
        ),
    ]
