# Generated by Django 5.1.5 on 2026-05-03 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_user_campus_user_card_issued_on_user_card_serial_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('cnic', models.CharField(db_index=True, help_text='Pakistani CNIC, normalised to 13 digits (no dashes)', max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/')),
                ('purpose', models.CharField(blank=True, help_text='e.g. "Job interview", "Document collection"', max_length=200)),
                ('host_department', models.CharField(blank=True, help_text='Where to send them', max_length=100)),
                ('status', models.CharField(choices=[('ON_CAMPUS', 'On campus'), ('CHECKED_OUT', 'Checked out'), ('DENIED', 'Denied entry')], default='ON_CAMPUS', max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ocr_raw_text', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('host_user', models.ForeignKey(blank=True, help_text='The campus account being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitors', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(blank=True, help_text='Security personnel who registered this visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'visitors',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['status', 'entry_time'], name='visitors_status_117199_idx'), models.Index(fields=['cnic', 'entry_time'], name='visitors_cnic_2753cb_idx'), models.Index(fields=['host_user', 'entry_time'], name='visitors_host_us_7cfef7_idx')],
            },
        ),
    ]
