# Generated by Django 5.1.5 on 2026-05-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0006_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='card_snapshot',
            field=models.ImageField(blank=True, help_text='Card frame captured at the gate. Auto-deleted after 30 days.', null=True, upload_to='gate_snapshots/card/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='face_snapshot',
            field=models.ImageField(blank=True, help_text='Face frame captured at the gate. Auto-deleted after 30 days.', null=True, upload_to='gate_snapshots/face/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='method',
            field=models.CharField(choices=[('BIOMETRIC', 'Facial Recognition'), ('CARD', 'University Card'), ('FACE_CARD', 'Face + Card Cross-Match'), ('RETINA', 'Retina Scan'), ('MANUAL', 'Manual Override')], default='BIOMETRIC', max_length=20),
        ),
    ]
